// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { Vote } from "./../common.sol";

// Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "VotesTable", typeId: RESOURCE_TABLE });`
ResourceId constant _tableId = ResourceId.wrap(0x74626170700000000000000000000000566f7465735461626c65000000000000);
ResourceId constant VotesTableTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0005020104010000000000000000000000000000000000000000000000000000
);

struct VotesTableData {
  uint32 timestamp;
  Vote vote;
  string note;
}

library VotesTable {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.BYTES32;
    _keySchema[1] = SchemaType.ADDRESS;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](3);
    _valueSchema[0] = SchemaType.UINT32;
    _valueSchema[1] = SchemaType.UINT8;
    _valueSchema[2] = SchemaType.STRING;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "requestId";
    keyNames[1] = "contributer";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "timestamp";
    fieldNames[1] = "vote";
    fieldNames[2] = "note";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get timestamp.
   */
  function getTimestamp(bytes32 requestId, address contributer) internal view returns (uint32 timestamp) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get timestamp.
   */
  function _getTimestamp(bytes32 requestId, address contributer) internal view returns (uint32 timestamp) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set timestamp.
   */
  function setTimestamp(bytes32 requestId, address contributer, uint32 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function _setTimestamp(bytes32 requestId, address contributer, uint32 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Get vote.
   */
  function getVote(bytes32 requestId, address contributer) internal view returns (Vote vote) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Vote(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get vote.
   */
  function _getVote(bytes32 requestId, address contributer) internal view returns (Vote vote) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return Vote(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set vote.
   */
  function setVote(bytes32 requestId, address contributer, Vote vote) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(vote)), _fieldLayout);
  }

  /**
   * @notice Set vote.
   */
  function _setVote(bytes32 requestId, address contributer, Vote vote) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(vote)), _fieldLayout);
  }

  /**
   * @notice Get note.
   */
  function getNote(bytes32 requestId, address contributer) internal view returns (string memory note) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get note.
   */
  function _getNote(bytes32 requestId, address contributer) internal view returns (string memory note) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set note.
   */
  function setNote(bytes32 requestId, address contributer, string memory note) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((note)));
  }

  /**
   * @notice Set note.
   */
  function _setNote(bytes32 requestId, address contributer, string memory note) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((note)));
  }

  /**
   * @notice Get the length of note.
   */
  function lengthNote(bytes32 requestId, address contributer) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of note.
   */
  function _lengthNote(bytes32 requestId, address contributer) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of note.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemNote(bytes32 requestId, address contributer, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of note.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemNote(bytes32 requestId, address contributer, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to note.
   */
  function pushNote(bytes32 requestId, address contributer, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to note.
   */
  function _pushNote(bytes32 requestId, address contributer, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from note.
   */
  function popNote(bytes32 requestId, address contributer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from note.
   */
  function _popNote(bytes32 requestId, address contributer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of note at `_index`.
   */
  function updateNote(bytes32 requestId, address contributer, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of note at `_index`.
   */
  function _updateNote(bytes32 requestId, address contributer, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 requestId, address contributer) internal view returns (VotesTableData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 requestId, address contributer) internal view returns (VotesTableData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 requestId, address contributer, uint32 timestamp, Vote vote, string memory note) internal {
    bytes memory _staticData = encodeStatic(timestamp, vote);

    PackedCounter _encodedLengths = encodeLengths(note);
    bytes memory _dynamicData = encodeDynamic(note);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 requestId, address contributer, uint32 timestamp, Vote vote, string memory note) internal {
    bytes memory _staticData = encodeStatic(timestamp, vote);

    PackedCounter _encodedLengths = encodeLengths(note);
    bytes memory _dynamicData = encodeDynamic(note);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 requestId, address contributer, VotesTableData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.timestamp, _table.vote);

    PackedCounter _encodedLengths = encodeLengths(_table.note);
    bytes memory _dynamicData = encodeDynamic(_table.note);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 requestId, address contributer, VotesTableData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.timestamp, _table.vote);

    PackedCounter _encodedLengths = encodeLengths(_table.note);
    bytes memory _dynamicData = encodeDynamic(_table.note);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 timestamp, Vote vote) {
    timestamp = (uint32(Bytes.slice4(_blob, 0)));

    vote = Vote(uint8(Bytes.slice1(_blob, 4)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(PackedCounter _encodedLengths, bytes memory _blob) internal pure returns (string memory note) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    note = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (VotesTableData memory _table) {
    (_table.timestamp, _table.vote) = decodeStatic(_staticData);

    (_table.note) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 requestId, address contributer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 requestId, address contributer) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 timestamp, Vote vote) internal pure returns (bytes memory) {
    return abi.encodePacked(timestamp, vote);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory note) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(note).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory note) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((note)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 timestamp,
    Vote vote,
    string memory note
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(timestamp, vote);

    PackedCounter _encodedLengths = encodeLengths(note);
    bytes memory _dynamicData = encodeDynamic(note);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 requestId, address contributer) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = requestId;
    _keyTuple[1] = bytes32(uint256(uint160(contributer)));

    return _keyTuple;
  }
}
