// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum VectorStatus {
  CHANNELING,
  DISCHARGING,
  ARCHIVED
}

enum MotionStatus {
  PENDING,
  PROCEEDING,
  HALTING,
  CANCELLED
}

enum ForceDirection {
  ALONG,
  AGAINST
}
