// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum ProjectStatus {
  CROWDING,
  INPROGRESS,
  ARCHIVED
}

enum RequestStatus {
  ACTIVE,
  CANCELLED,
  CLAIMED
}

enum ApprovalStatus {
  REJECTED,
  ACCEPTED,
  PENDING
}

enum Vote {
  APPROVED,
  DECLINED
}
