// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CSProjectsMetadataTable, CSProjectsMetadataTableData } from "./tables/CSProjectsMetadataTable.sol";
import { CSProjectsDataTable, CSProjectsDataTableData } from "./tables/CSProjectsDataTable.sol";
