// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ProjectsMetadataTable, ProjectsMetadataTableData } from "./tables/ProjectsMetadataTable.sol";
import { ProjectsDataTable, ProjectsDataTableData } from "./tables/ProjectsDataTable.sol";
import { ContributersTable, ContributersTableData } from "./tables/ContributersTable.sol";
import { RequestsMetadataTable, RequestsMetadataTableData } from "./tables/RequestsMetadataTable.sol";
import { RequestsDataTable, RequestsDataTableData } from "./tables/RequestsDataTable.sol";
import { VotesTable, VotesTableData } from "./tables/VotesTable.sol";
