// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CSVectorsTable, CSVectorsTableData } from "./tables/CSVectorsTable.sol";
import { CSVectorMotionsLookupTable } from "./tables/CSVectorMotionsLookupTable.sol";
import { CSMotionsTable, CSMotionsTableData } from "./tables/CSMotionsTable.sol";
import { CSMotionForcesLookupTable } from "./tables/CSMotionForcesLookupTable.sol";
import { CSForcesTable, CSForcesTableData } from "./tables/CSForcesTable.sol";
import { CSPotentialsTable, CSPotentialsTableData } from "./tables/CSPotentialsTable.sol";
import { CSVectorPotentialsLookupTable } from "./tables/CSVectorPotentialsLookupTable.sol";
