// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ForceDirection } from "./../common.sol";

/**
 * @title ICSForceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSForceSystem {
  function csp__applyForce(
    bytes32 motionId,
    ForceDirection direction,
    string memory insight
  ) external returns (bytes32);
}
