// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICSProjectSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSProjectSystem {
  function csp__createProject(
    bytes32 symbol,
    bytes32 codename,
    uint256 threshold,
    uint256 target,
    string memory title,
    string memory description
  ) external returns (bytes32);
}
