// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICSProjectSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSProjectSystem {
  function csp__create(
    uint32 threshold,
    uint32 target,
    uint32 deadline,
    string memory title,
    string memory description
  ) external;

  function csp__archive(bytes32 projectId) external;

  function csp__claim(bytes32 projectId) external;

  function csp__contribute(bytes32 projectId, uint256 amount) external;

  function csp__request(
    bytes32 projectId,
    address recepient,
    uint256 amount,
    string memory title,
    string memory description
  ) external;
}
