// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICSProtocolSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSProtocolSystem {
  function app__registerERC20Token(uint256 smartObjectId, address tokenAddress, address receiver) external;

  function app__updateERC20Receiver(uint256 smartObjectId, address receiver) external;

  function app__collectTokens(uint256 smartObjectId) external;
}
