// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ForceDirection } from "./../common.sol";

/**
 * @title ICSPSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSPSystem {
  function csp__toggleInfiniteApprove() external returns (address);

  function csp__grantApproval(uint amount) external returns (address);

  function csp__initiateVector(uint256 capacity, uint256 lifetime, string memory insight) external returns (bytes32);

  function csp__archiveVector(bytes32 vectorId) external;

  function csp__transferVector(bytes32 vectorId, address newHandler) external;

  function csp__initiateMotion(
    bytes32 vectorId,
    uint256 momentum,
    uint256 lifetime,
    address target,
    string memory insight
  ) external returns (bytes32);

  function csp__executeMotion(bytes32 motionId) external payable;

  function csp__cancelMotion(bytes32 motionId) external;

  function csp__storeEnergy(bytes32 vectorId, uint256 strength) external payable returns (address);

  function csp__releaseEnergy(bytes32 vectorId) external payable;

  function csp__applyForce(
    bytes32 motionId,
    ForceDirection direction,
    string memory insight
  ) external returns (bytes32);
}
