// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICSRequestSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICSRequestSystem {
  function csp__cancel(bytes32 requestId) external;

  function csp__proceed(bytes32 requestId) external;
}
